feat: add 'from' method which populates Transaction from encoded base…
sol4k/sol4k pull request #47
Opened 2023-08-21 05:27 UTC by Bentl22a9

…64 transaction string

2023-08-21 10:14 UTC, Shpota commented
Thank you for the contribution. I will review it shortly.

2023-08-21 11:32 UTC, Shpota requested changes
Please merge the latest `main` into your branch. I have added a fix for running CI on external PRs

2023-08-21 11:32 UTC, Shpota commented on src/main/kotlin/org/sol4k/Transaction.kt
> +                val signaturesCount = Binary.decodeLength(byteArray)
You can deconstruct it straight away here. EG:
```
val (len, byteArray) = Binary.decodeLength(byteArray)
```
There are a couple of places where you can use it.

2023-08-21 11:32 UTC, Shpota commented on src/main/kotlin/org/sol4k/Transaction.kt
> +                val numRequiredSignatures = byteArray.first().toInt().also { byteArray = byteArray.drop(1).toByteArray() }
Is there a specific reason for using `also` here? If not, please split it into two lines/calls, because it is complicated

2023-08-22 00:58 UTC, Bentl22a9 commented on build.gradle
> -    id 'com.vanniktech.maven.publish' version '0.25.2'
I faced a build error when I tried to include the forked version in my app. I checked the build.log file on jitpack, saying jvmTarget conflicts.

2023-08-22 01:16 UTC, Bentl22a9 commented
Thanks for the review!

BTW do you have any plan to support a versioned transaction? 
I've found some dApps such as Raydium(https://raydium.io/swap) where users can opt-in between legacy and versioned transactions.

2023-08-22 09:21 UTC, Shpota commented
Please ignore the failure of integration tests for now. There is a misconfiguration that prevents accessing environment variables for PRs created by external contributors. I am working on fixing it. The build and linter issues are valid.

2023-09-01 05:23 UTC, closed without merging