Decode transaction from string, fix transaction serialization bug
sol4k/sol4k pull request #65
Opened 2024-05-13 02:46 UTC by Tougee

2024-05-13 12:02 UTC, Shpota requested changes
Thank you for the contribution

2024-05-13 12:02 UTC, Shpota commented on src/main/kotlin/org/sol4k/Transaction.kt
> +                ).apply {
I would suggest adding transactions is a separate call instead of calling `apply`

2024-05-13 12:02 UTC, Shpota commented on src/main/kotlin/org/sol4k/Transaction.kt
> +            } catch (e: Exception) {
If the error is just re-thrown, the try-catch block carries no value. Let's unwrap it

2024-05-14 02:36 UTC, Tougee commented on src/main/kotlin/org/sol4k/Binary.kt
> +    fun decodeLength(bytes: ByteArray): Pair<Int, ByteArray> {
good point

2024-05-14 02:51 UTC, Tougee commented on src/main/kotlin/org/sol4k/Transaction.kt
> +                val signaturesCount = Binary.decodeLength(byteArray)
use `DecodedLength` instead now

2024-05-14 09:59 UTC, Shpota commented
Hey @Tougee could you please check the linter again? Looks like you fixed the issues in the test files but not in the main source set. You can run `./gradlew build` to execute all the checks locally. Also, it applies standard IntelliJ IDE formatting so you can just reformat it in the IDE and that should be enough.

2024-05-14 12:48 UTC, Shpota approved these changes

2024-05-14 12:49 UTC, merged

2024-05-14 13:21 UTC, Shpota commented
Thank you @Tougee. The changes are now available in v0.4.2